【WIP】feat: add write read split
dubbogo/arana pull request #46
Opened 2022-01-17 16:28 UTC by Lvnszn

**What this PR does**:
add read write split. https://dubbo-kylin.yuque.com/staff-rvuh2g/qau55u/nshtei
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-01-18 06:36 UTC, dk-lockdown commented on pkg/executor/redirect.go
> +	log.Infof(query)
generateSql 是不需要的，这个是我的疏忽，`query := ctx.Stmt.StmtNode.Text()` 就行了，因为现在后端支持了 prepare 二进制协议，不需要再把参数拼到 sql 里用 text 协议执行。

2022-01-18 06:36 UTC, dk-lockdown commented on pkg/executor/redirect.go
comQuery 也会有读写分离

2022-01-19 13:02 UTC, Lvnszn commented on pkg/executor/redirect.go
> +	log.Infof(query)
addressed

2022-01-19 13:02 UTC, Lvnszn commented on pkg/executor/redirect.go
comQuery 里面的 query 跟 comStmt 还有点区别。我得研究研究

2022-01-24 02:27 UTC, jjeffcaii commented on pkg/selector/weight_random.go
> +	areaSize := len(w.weightAreaEnds)
权重的算法有点问题，性能较佳的算法举例，节点`A,B,C` 的权重分别是 `3,10,8`，那么计算法则是:
1. 生成BTree, 一次是 `3 -> A`, `3+10 -> B`, `3+10+8 -> C`，并记录sum
2. 生成rand(0-sum)，然后取BTree里向上最接近的值
BTree可以依赖google的实现, https://github.com/google/btree

2022-01-24 02:27 UTC, jjeffcaii requested changes
pls fix

2022-01-24 03:17 UTC, jjeffcaii approved these changes
pls add ut

2022-01-24 15:29 UTC, Lvnszn commented
> pls add ut

addressed

2022-01-26 00:43 UTC, dk-lockdown approved these changes

2022-01-29 09:37 UTC, AlexStocks approved these changes

2022-02-06 12:28 UTC, Lvnszn commented on pkg/executor/redirect.go
> +		}
addressed

2022-02-08 03:52 UTC, Lvnszn commented
PTAL @AlexStocks

2022-02-08 13:55 UTC, merged